services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      primary-network:
        ipv4_address: 172.10.0.100
    security_opt:
      - no-new-privileges:true
    restart: always
    user: $PUID:$PGID
    # devices:
      # - /dev/dri:/dev/dri # for hardware transcoding
    ports:
      - "8096:8096"
    environment:
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DATADIR/Movies:/data/movies # Media Folder 1
      - $DATADIR/TV Shows:/data/tv shows # Media Folder 2
      - $DATADIR/Animations:/data/animations # Media Folder 3
      - $DATADIR/Anime shows:/data/anime show # Media Folder 4
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
