services:
  # Radarr - Movie management
  radarr:
    security_opt:
      - no-new-privileges:true
    restart: "no"
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DATADIR/Downloads/torrent-data:/downloads
      - $DATADIR:/Media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID