services:
  # Sonarr - TV Shows Management
  sonarr:
    security_opt:
      - no-new-privileges:true
    restart: "no"
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATADIR/Downloads/torrent-data:/downloads
      - $DATADIR:/Media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID