services:
  # Jackett - Torrent proxy
  jackett:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    volumes:
      - $DOCKERDIR/appdata/jackett:/config
      - $DATADIR/Downloads/torrent-black-hole:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
