services:
    kavita:
        image: jvmilazz0/kavita:latest 
        container_name: kavita
        security_opt:
          - no-new-privileges:true
        restart: unless-stopped
        networks:
          - primary-network
        ports:
          - "5000:5000"
        volumes:
            - $DOCKERDIR/appdata/kavita/manga:/manga 
            - $DOCKERDIR/appdata/kavita/comics:/comics
            - $DOCKERDIR/appdata/kavita/books:/books
            - $DOCKERDIR/appdata/kavita/data:/kavita/config
        environment:
          - TZ=$TZ
